### ISSUE TITLE
Cannot add space between the equations

### ISSUE THREAD

**Issue by athiranibinb** [insoutt/tinymce-equation-editor#38]
Integrated this plugin in tinymce editor. But cannot add space in-between the equation.

For eg, I added sin10cos10 .After adding that, i cannot add space between sin10 and cos 10.

![image](https://user-images.githubusercontent.com/88190634/211533094-c2404f1b-417a-48d4-8377-2ef94a6afc49.png)

**Comment by insoutt** [comment]
Hi @athiranibinb why do you need to add space after each function? Mathlive by default add space between functions to to make it easy to read, here is an example:

![Screenshot](https://i.imgur.com/po0NQ2c.png)

Or if you want to add spaces, you can insert the function in the editor, then add space and then add another function.


![Screenshot 2](https://i.imgur.com/2kW56Ep.png)
